---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-autoscaler-deployment
  namespace: cluster-autoscaller-examples
spec:
  replicas: 50
  selector:
    matchLabels:
      app: simple-autoscaler
  template:
    metadata:
      labels:
        app: simple-autoscaler
    spec:
      containers:
        - name: echoserver
          image: ealen/echo-server
          ports:
            - containerPort: 80
