---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-autoscaller-simple-autoscaler

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: cluster-autoscaller-simple-autoscaler
spec:
  replicas: 50
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: echoserver
          image: ealen/echo-server
          ports:
            - containerPort: 80
