---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-pvc
  namespace: ebs-examples
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: ebs-examples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.8
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx
              mountPath: /usr/share/nginx/html
              readOnly: false
      volumes:
        - name: nginx
          persistentVolumeClaim:
            claimName: simple-pvc
