---
apiVersion: v1
kind: Namespace
metadata:
  name: ebs-example-failed-mount

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-pvc
  namespace: ebs-example-failed-mount
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: ebs-example-failed-mount
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.8
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx
              mountPath: /usr/share/nginx/html
              readOnly: false
      volumes:
        - name: nginx
          persistentVolumeClaim:
            claimName: simple-pvc
