---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd

  # remove resources when deleting application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LukaK/aws-eks-infrastructure.git
    targetRevision: argocd
    path: services/apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true     # delete resources
      selfHeal: true  # drift override
    syncOptions:
      - Validate=true          # validate deployment fields
      - CreateNamespace=false  # don't create namespaces automatically
      - PrunePropagationPolicy=foreground
      - PruneLast=true
