---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "dns-01-{{ .Chart.Name }}"
spec:
  acme:
    email: {{ required "A valid .Values.email required" .Values.email | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: "dns-01-{{ .Chart.Name }}-cluster-issuer"
    solvers:
      - selector:
          dnsZones:
            - {{ required "A valid .Values.dnsZone required." .Values.dnsZone | quote }}
        dns01:
          route53:
            region: {{ required "A valid .Values.region required." .Values.region | quote }}
            hostedZoneID: {{ required "A valid .Values.hostedZoneId required." .Values.hostedZoneId | quote }}
