---
global:
  domain: "argocd.${hosted_zone_name}"

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: ${ingress_class_name}
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: ${cluster_issuer_name}
    extraTls:
      - hosts:
          - "argocd.${hosted_zone_name}"
        secretName: argocd-public-endpoint
