---
global:
  domain: argocd.api.itguyjournals.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: external-nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: dns-01-cluster-issuer
    extraTls:
      - hosts:
          - argocd.api.itguyjournals.com
        secretName: argocd-api-itguyjournals-com
