---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: hpa-example
spec:
  # Dont add replicaes if you are using ArgoCD or other syncing solutions with hpa
  # replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: registry.k8s.io/hpa-example
          name: myapp
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m

