---
apiVersion: v1
kind: Namespace
metadata:
  name: hpa-example-simple-hpa


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: hpa-example-simple-hpa
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: registry.k8s.io/hpa-example
          name: myapp
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: hpa-example-simple-hpa
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: http


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
  namespace: hpa-example-simple-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
