name: "CI pipeline"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}


permissions:
  contents: read


jobs:

  scan-for-security-issues:

    name: Security Scan

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan terraform files for misconfiguration
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: .config/trivy.yaml


  validate-infrastructure:

    name: Terragrunt Infrastructure Checks

    runs-on: ubuntu-latest

    env:
      tf_version: '1.9.4'
      tg_version: '0.58.10'
      working_dir: 'infrastructure/live'

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure configuration is valid
        uses: gruntwork-io/terragrunt-action@v2
        id: terragrunt-validate
        with:
          tg_dir: ${{ env.working_dir }}
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_command: 'run-all validate'
