name: "CI pipeline"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}


permissions:
  contents: read


jobs:

  scan-for-security-issues:

    name: Security Scan

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan terraform files for misconfiguration
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: .config/trivy.yaml
